[common]
version = 2
import_std = [
    "fs",
    "net",
    "process",
]

[sandbox]
kind = "Disabled"

[pkg.peg-macros]
allow_proc_macro = true

[pkg.lazy_static]
allow_unsafe = true

[pkg.float-ord]
allow_unsafe = true

[pkg.hashbrown]
allow_unsafe = true

[pkg.proc-macro2]
build.allow_apis = [
    "fs",
    "process",
]
allow_unsafe = true

[pkg.log]
allow_unsafe = true

[pkg.indexmap]
allow_unsafe = true

[pkg.eson]
allow_apis = [
    "fs",
]

[pkg.itertools]
allow_unsafe = true

[pkg.unicode-ident]
allow_unsafe = true

[pkg.derive_more-impl]
allow_proc_macro = true

[pkg.dyn-clone]
allow_unsafe = true

[pkg.syn]
allow_unsafe = true

[pkg.either]
allow_unsafe = true
